version: "3.0"
services:
  web:
    build: .
    image: open2-application
    env_file:
        .env
    environment:
        DB_HOST: "database"
        DB_NAME: "${DATABASE_NAME}"
        DB_USER: "root"
        DB_PASS: "${DATABASE_ROOT_PASSWORD}"
    ports:
      - "127.0.0.1:8443:443"
    #Decommentare per poter lavorare direttamente sulla directory root
    #volumes:
    #  - .:/var/www/app
    depends_on:
      - database
    networks:
      open2net:
  database:
    image: mariadb
    restart: always
    env_file:
        .env
    environment:
      MARIADB_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DATABASE_NAME}"   
    volumes:
      - dbdata:/var/lib/mysql
      - applog:/var/log
    expose:
      - "3306"
    ports:
      - "127.0.0.1:8306:3306"
    networks:
      open2net:
volumes:
  applog: {}
  dbdata: {}
networks:
  open2net:
