#!/usr/bin/env php
<?php
use open20\amos\core\applications\CmsBoot;


 
/* 
 Use ENC_KEY for encript properties.
 export ENC_KEY=1234567890 // from platform env.
 
 For test use:
 
 putenv("ENC_KEY=1234567890");
*/


// loaders array
$loaders = [];
foreach ([getcwd(), __DIR__, ''] as $prefix) {
	$loaders[] = [$prefix];
	$loaders[] = [$prefix, '..'];
	$loaders[] = [$prefix, '..', '..'];
	$loaders[] = [$prefix, '..', '..', '..'];
	$loaders[] = [$prefix, '..', '..', '..', '..'];
}
// find vendor if exists
foreach ($loaders as $file) {
	$path = implode(DIRECTORY_SEPARATOR, $file);
	foreach ([DIRECTORY_SEPARATOR, ''] as $slash) {
		$file = $path . $slash . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';
		if (file_exists($file)) {
			require_once($file);
			$vendor = pathinfo($file, PATHINFO_DIRNAME);
			break 2;
		}
	}	
}

$configFilePaths = [__DIR__ . '/frontend/configs/env.php', 'configs/env.php'];
foreach ($configFilePaths as $configFile) {
	if (file_exists($configFile)) {
		break;
	}
}
$boot = new CmsBoot();
$boot->configFile =  $configFile;
$boot->setBaseYiiFile($vendor . '/yiisoft/yii2/Yii.php');
$boot->applicationConsole();
